services:
  postgres:
    image: postgres:latest
    container_name: vkpostanalyzer-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vkpostanalyzer
    ports:
      - "5432:5432"
    volumes:
      - vk-postanalyzer-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  vk-postanalyzer-postgres-data: 
